(deftheme kanagawa-lotus
  "The Kanagawa lotus theme")

(custom-theme-set-faces
 'kanagawa-lotus
 '(button ((t (:underline t))))
 '(link ((t :foreground "#6693bf" :underline t :weight bold)))
 '(link-visited ((t :foreground "#4d699b" :underline t :weight normal)))
 '(cursor ((t (:foreground "#f2ecbc" :background "#545464"))))
 '(widget-field ((t (:foreground "#545464" :background "#e7dba0"))))
 '(escape-glyph ((t (:foreground "#766b90" :weight bold))))
 '(fringe ((t (:background "#f2ecbc" :foreground "#545464"))))
 '(header-line ((t (:foreground "#545464" :background "#e7dba0" :extend t))))
 '(highlight ((t (:foreground "#545464" :background "#dcd5ac" :weight bold))))
 '(success ((t (:foreground "#6f894e" :weight bold))))
 '(warning ((t (:foreground "#e98a00" :weight bold))))
 '(tooltip ((t (:foreground "#43436c" :background "#c7d7e0"))))
 '(menu ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(region ((t (:background "#c9cbd1"))))
 '(separator-line ((t (:background "#d5cea3"))))
 '(shadow ((t (:inherit separator-line))))
 '(window-border ((t (:background "#f2ecbc"))))
 '(window-divider ((t (:foreground "#e5ddb0"))))
 '(vertical-border ((t (:foreground "#e5ddb0"))))
 '(font-lock-builtin-face ((t (:foreground "#c84053"))))
 '(font-lock-comment-face ((t (:foreground "#8a8980"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#8a8980"))))
 '(font-lock-bracket-face ((t (:foreground "#4e8ca2"))))
 '(font-lock-delimiter-face ((t (:foreground "#4e8ca2"))))
 '(font-lock-constant-face ((t (:foreground "#cc6d00"))))
 '(font-lock-doc-face ((t (:foreground "#6f894e"))))
 '(font-lock-function-name-face ((t (:foreground "#4d699b"))))
 '(font-lock-keyword-face ((t (:foreground "#624c83" :weight bold))))
 '(font-lock-operator-face ((t (:foreground "#836f4a"))))
 '(font-lock-negation-char-face ((t (:inherit font-lock-keyword-face))))
 '(font-lock-preprocessor-face ((t (:foreground "#c84053"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#836f4a" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#836f4a" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#6f894e"))))
 '(font-lock-number-face ((t (:foreground "#b35b79"))))
 '(font-lock-type-face ((t (:foreground "#597b75"))))
 '(font-lock-variable-name-face ((t (:foreground nil))))
 '(font-lock-property-use-face ((t (:foreground "#77713f"))))
 '(font-lock-warning-face ((t (:foreground "#e98a00"))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(line-number ((t (:background "#f2ecbc" :foreground "#8a8980"))))
 '(line-number-current-line ((t (:background "#f2ecbc" :foreground "#cc6d00"))))
 '(ansi-color-black ((t (:foreground "#1F1F28"))))
 '(ansi-color-red ((t (:foreground "#c84053"))))
 '(ansi-color-green ((t (:foreground "#6f894e"))))
 '(ansi-color-yellow ((t (:foreground "#77713f"))))
 '(ansi-color-blue ((t (:foreground "#4d699b"))))
 '(ansi-color-magenta ((t (:foreground "#b35b79"))))
 '(ansi-color-cyan ((t (:foreground "#597b75"))))
 '(ansi-color-white ((t (:foreground "#545464"))))
 '(ansi-color-bright-black ((t (:foreground "#8a8980"))))
 '(ansi-color-bright-red ((t (:foreground "#d7474b"))))
 '(ansi-color-bright-green ((t (:foreground "#6e915f"))))
 '(ansi-color-bright-yellow ((t (:foreground "#836f4a"))))
 '(ansi-color-bright-blue ((t (:foreground "#6693bf"))))
 '(ansi-color-bright-magenta ((t (:foreground "#624c83"))))
 '(ansi-color-bright-cyan ((t (:foreground "#5e857a"))))
 '(ansi-color-bright-white ((t (:foreground "#43436c"))))
 '(isearch ((t (:foreground "#dcd7ba" :background "#e98a00"))))
 '(isearch-fail ((t (:foreground "#545464" :background "#e82424"))))
 '(lazy-highlight ((t (:foreground "#545464" :background "#b5cbd2"))))
 '(minibuffer-prompt ((t (:foreground "#545464" :weight bold))))
 '(mode-line ((t (:foreground "#43436c" :background "#d5cea3"))))
 '(mode-line-inactive ((t (:foreground "#8a8980" :background "#d5cea3"))))
 '(hl-line ((t (:background "#e4d794"))))
 '(message-header-name ((t (:foreground "#e7dba0"))))
 '(message-header-other ((t (:foreground "#e98a00"))))
 '(message-header-subject ((t (:foreground "#836f4a"))))
 '(message-header-to ((t (:foreground "#545464"))))
 '(message-header-cc ((t (:foreground "#5e857a"))))
 '(message-header-xheader ((t (:foreground "#545464"))))
 '(erc-action-face ((t (:inherit erc-default-face))))
 '(erc-bold-face ((t (:weight bold))))
 '(erc-current-nick-face ((t (:foreground "#cc6d00" :weight bold))))
 '(erc-direct-msg-face ((t (:inherit erc-default-face))))
 '(erc-error-face ((t (:foreground "#e98a00"))))
 '(erc-fool-face ((t (:inherit erc-default-face))))
 '(erc-input-face ((t (:foreground "#545464"))))
 '(erc-keyword-face ((t (:inherit font-lock-keyword-face))))
 '(erc-nick-default-face ((t (:foreground "#6693bf" :weight bold))))
 '(erc-my-nick-face ((t (:foreground "#c84053"))))
 '(erc-notice-face ((t (:foreground "#6f894e"))))
 '(erc-prompt-face ((t (:inherit minibuffer-prompt))))
 '(erc-timestamp-face ((t (:inherit font-lock-keyword-face))))
 '(erc-underline-face ((t (:underline t))))
 '(term ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(term-color-black ((t (:foreground "#1F1F28" :background "#1F1F28"))))
 '(term-color-red ((t (:foreground "#c84053" :background "#c84053"))))
 '(term-color-green ((t (:foreground "#6f894e" :background "#6f894e"))))
 '(term-color-yellow ((t (:foreground "#77713f" :background "#77713f"))))
 '(term-color-blue ((t (:foreground "#4d699b" :background "#4d699b"))))
 '(term-color-magenta ((t (:foreground "#b35b79" :background "#b35b79"))))
 '(term-color-cyan ((t (:foreground "#597b75" :background "#597b75"))))
 '(term-color-white ((t (:foreground "#545464" :background "#545464"))))
 '(org-done ((t (:foreground "#5a7785"))))
 '(org-code ((t (:background "#d5cea3"))))
 '(org-meta-line ((t (:foreground "#6f894e" :background "#b7d0ae"))))
 '(org-block ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(org-block-begin-line ((t (:foreground "#6693bf" :background "#d7e3d8"))))
 '(org-block-end-line ((t (:foreground "#e82424" :background "#d9a594"))))
 '(org-headline-done ((t (:foreground "#5a7785" :strike-through t))))
 '(org-todo ((t (:foreground "#e98a00" :weight bold))))
 '(org-headline-todo ((t (:foreground "#e5ddb0"))))
 '(org-upcoming-deadline ((t (:foreground "#e98a00"))))
 '(org-footnote ((t (:foreground "#5e857a"))))
 '(org-indent ((t (:foreground "#f2ecbc" :background "#f2ecbc"))))
 '(org-hide ((t (:inherit org-indent))))
 '(org-date ((t (:foreground "#6693bf"))))
 '(org-ellipsis ((t (:foreground "#b5cbd2" :weight bold))))
 '(org-level-1 ((t (:foreground "#b35b79" :height 1.3 :weight bold))))
 '(org-level-2 ((t (:foreground "#4d699b" :height 1.2 :weight bold))))
 '(org-level-3 ((t (:foreground "#5e857a" :height 1.1))))
 '(org-level-4 ((t (:foreground "#6e915f"))))
 '(org-level-5 ((t (:foreground "#836f4a"))))
 '(org-level-6 ((t (:foreground "#e98a00"))))
 '(org-level-7 ((t (:foreground "#c84053"))))
 '(org-level-8 ((t (:foreground "#624c83"))))
 '(org-priority ((t (:foreground "#e82424" :weight bold))))
 '(show-paren-match ((t (:foreground "#e98a00" :weight bold))))
 '(show-paren-match-expression ((t (:inherit show-paren-match))))
 '(show-paren-mismatch ((t (:foreground "#8a8980" :weight bold))))
 '(tab-line ((t (:background "#d5cea3"))))
 '(comint-highlight-prompt ((t (:background "#4e8ca2" :foreground "#dcd5ac"))))
 '(completions-annotations ((t (:background unspecified :foreground "#5a7785"))))
 '(dired-directory ((t (:foreground "#624c83" :inherit bold))))
 '(dired-flagged ((t (:foreground "#c84053"))))
 '(dired-header ((t (:foreground "#43436c" :weight bold))))
 '(dired-ignored ((t (:inherit shadow))))
 '(dired-mark ((t (:foreground "#c84053" :inherit bold))))
 '(dired-marked ((t (:foreground "#b35b79" :inherit bold))))
 '(dired-perm-write ((t (:foreground "#545464" :underline t))))
 '(dired-symlink ((t (:foreground "#597b75"))))
 '(dired-warning ((t (:foreground "#e98a00"))))
 '(highlight-indent-guides-character-face ((t (:foreground "#f2ecbc"))))
 '(highlight-indent-guides-stack-character-face ((t (:foreground "#f2ecbc"))))
 '(highlight-indent-guides-stack-odd-face ((t (:foreground "#f2ecbc"))))
 '(highlight-indent-guides-stack-even-face ((t (:foreground "#a09cac"))))
 '(highlight-indent-guides-stack-character-face ((t (:foreground "#f2ecbc"))))
 '(highlight-indent-guides-even-face ((t (:foreground "#d5cea3"))))
 '(highlight-indent-guides-odd-face ((t (:foreground "#a09cac"))))
 '(ivy-current-match ((t (:foreground "#d5cea3" :background "#4d699b" :weight bold))))
 '(ivy-action ((t (:foreground "#545464"))))
 '(ivy-grep-line-number ((t (:foreground "#6e915f"))))
 '(ivy-minibuffer-match-face-1 ((t (:foreground "#c84053"))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit ivy-grep-line-number))))
 '(ivy-minibuffer-match-highlight ((t (:foreground "#4d699b"))))
 '(ivy-grep-info ((t (:foreground "#4d699b"))))
 '(ivy-grep-line-number ((t (:foreground "#4e8ca2"))))
 '(ivy-confirm-face ((t (:foreground "#5e857a"))))
 '(ivy-posframe ((t (:background "#e5ddb0"))))
 '(ivy-posframe-border ((t (:background "#f2ecbc"))))
 '(helm-bookmark-directory ((t (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((t (:foreground "#b35b79"))))
 '(helm-bookmark-gnus ((t (:foreground "#b35b79"))))
 '(helm-bookmark-info ((t (:foreground "#b35b79"))))
 '(helm-bookmark-man ((t (:foreground "#b35b79"))))
 '(helm-bookmark-w3m ((t (:foreground "#b35b79"))))
 '(helm-buffer-directory ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(helm-buffer-file ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(helm-buffer-not-saved ((t (:foreground "#b35b79" :background "#f2ecbc"))))
 '(helm-buffer-process ((t (:foreground "#624c83" :background "#f2ecbc"))))
 '(helm-buffer-saved-out ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(helm-buffer-size ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(helm-candidate-number ((t (:background "#f2ecbc" :foreground "#624c83" :inherit bold))))
 '(helm-ff-directory ((t (:foreground "#624c83" :background "#f2ecbc" :inherit bold))))
 '(helm-ff-dotted-directory ((t (:foreground "#624c83" :background "#f2ecbc" :inherit bold))))
 '(helm-ff-dotted-symlink-directory ((t (:foreground "#597b75" :background "#f2ecbc" :inherit bold))))
 '(helm-ff-executable ((t (:foreground "#6f894e" :background "#f2ecbc" :weight normal))))
 '(helm-ff-file ((t (:foreground "#545464" :background "#f2ecbc" :weight normal))))
 '(helm-ff-invalid-symlink ((t (:foreground "#c84053" :background "#f2ecbc" :inherit bold))))
 '(helm-ff-prefix ((t (:foreground "#f2ecbc" :background "#624c83" :weight normal))))
 '(helm-ff-symlink ((t (:foreground "#597b75" :background "#f2ecbc" :inherit bold))))
 '(helm-grep-cmd-line ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(helm-grep-file ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(helm-grep-finish ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(helm-grep-lineno ((t (:foreground "#597b75" :background "#f2ecbc" :inherit bold))))
 '(helm-grep-match ((t (:foreground unspecified :background unspecified :inherit helm-match))))
 '(helm-header ((t (:foreground "#545464" :background "#f2ecbc" :underline nil :box nil))))
 '(helm-match ((t (:foreground "#6f894e"))))
 '(helm-match-item ((t (:foreground "#6f894e"))))
 '(helm-moccur-buffer ((t (:foreground nil :background "#f2ecbc"))))
 '(helm-selection ((t (:background "#c9cbd1"))))
 '(helm-selection-line ((t (:background "#e5ddb0"))))
 '(helm-separator ((t (:foreground "#b35b79" :background "#f2ecbc"))))
 '(helm-source-header ((t (:background "#b35b79" :foreground "#f2ecbc" :inherit bold))))
 '(helm-time-zone-current ((t (:foreground "#624c83" :background "#f2ecbc"))))
 '(helm-time-zone-home ((t (:foreground "#b35b79" :background "#f2ecbc"))))
 '(helm-visible-mark ((t (:foreground "#624c83" :background "#d5cea3"))))
 '(helm-swoop-target-line-block-face ((t (:foreground "#545464" :background "#dcd5ac"))))
 '(helm-swoop-target-line-face ((t (:background "#dcd5ac"))))
 '(helm-swoop-target-word-face ((t (:background "#dcd5ac" :foreground "#e98a00"))))
 '(treemacs-directory-collapsed-face ((t (:foreground "#545464"))))
 '(treemacs-directory-face ((t (:inherit treemacs-directory-collapsed-face))))
 '(treemacs-file-face ((t (:inherit treemacs-directory-face))))
 '(treemacs-git-added-face ((t (:foreground "#e98a00"))))
 '(treemacs-git-renamed-face ((t (:inherit treemacs-file-face))))
 '(treemacs-git-ignored-face ((t (:foreground "#e7dba0"))))
 '(treemacs-git-unmodified-face ((t (:inhert treemacs-git-renamed-face))))
 '(treemacs-git-renamed-face ((t (:inhert treemacs-git-unmodified-face))))
 '(treemacs-git-modified-face ((t (:foreground "#6e915f"))))
 '(lsp-headerline-breadcrumb-path-error-face ((t (:underline (:color "#6e915f" :style wave) :foreground "#e7dba0" :background "#d5cea3"))))
 '(lsp-headerline-breadcrumb-path-face ((t (:background "#d5cea3"))))
 '(lsp-headerline-breadcrumb-path-hint-face ((t (:foreground "#5e857a"))))
 '(lsp-headerline-breadcrumb-path-info-face ((t (:foreground "#5a7785"))))
 '(lsp-headerline-breadcrumb-separator-face ((t (:inherit lsp-headerline-breadcrumb-path-face))))
 '(lsp-headerline-breadcrumb-symbols-face ((t (:inherit lsp-headerline-breadcrumb-path-face))))
 '(lsp-headerline-breadcrumb-project-prefix-face ((t (:inherit lsp-headerline-breadcrumb-path-face))))
 '(lsp-headerline-breadcrumb-symbols-error-face ((t (:foreground "#e82424"))))
 '(lsp-ui-doc-background ((t (:foreground "#e82424" :background "#d5cea3"))))
 '(lsp-ui-doc-header ((t (:inherit lsp-ui-doc-background))))
 '(lsp-ui-doc-border ((t (:background unspecified :foreground unspecified))))
 '(lsp-ui-peek-peek ((t (:background "#dcd5ac"))))
 '(lsp-ui-peek-list ((t (:background "#d5cea3"))))
 '(lsp-ui-peek-filename ((t (:foreground "#4d699b"))))
 '(lsp-ui-peek-line-number ((t (:foreground "#a09cac"))))
 '(lsp-ui-peek-highlight ((t (:foreground "#545464" :background "#b5cbd2" :box (:line-width -1 :color "#5a7785")))))
 '(lsp-ui-peek-header ((t (:foreground "#545464" :background "#c7d7e0" :bold t))))
 '(lsp-ui-peek-footer ((t (:inherit lsp-ui-peek-header))))
 '(lsp-ui-peek-selection ((t (:foreground "#545464" :background "#9fb5c9"))))
 '(lsp-ui-sideline-code-action ((t (:foreground "#836f4a"))))
 '(lsp-ui-sideline-current-symbol ((t (:foreground "#6693bf"))))
 '(lsp-ui-sideline-symbol ((t (:foreground "#5a7785"))))
 '(rainbow-delimiters-mismatched-face ((t (:foreground "#e82424"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#5e857a"))))
 '(rainbow-delimiters-base-error-face ((t (:foreground "#e82424"))))
 '(rainbow-delimiters-base-face ((t (:foreground "#e7dba0"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#4e8ca2"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#5a7785"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#624c83"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#6e915f"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#5e857a"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#836f4a"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#e82424"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#4d699b"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#4e8ca2"))))
 '(swiper-line-face ((t (:foreground "#836f4a"))))
 '(swiper-background-match-face-1 ((t (:foreground "#d5cea3" :background "#cc6d00"))))
 '(swiper-background-match-face-2 ((t (:foreground "#d5cea3" :background "#4d699b"))))
 '(swiper-background-match-face-3 ((t (:foreground "#d5cea3" :background "#77713f"))))
 '(swiper-background-match-face-4 ((t (:foreground "#d5cea3" :background "#e82424"))))
 '(swiper-match-face-1 ((t (:inherit swiper-background-match-face-1))))
 '(swiper-match-face-2 ((t (:inherit swiper-background-match-face-2))))
 '(swiper-match-face-3 ((t (:inherit swiper-background-match-face-3))))
 '(swiper-match-face-4 ((t (:inherit swiper-background-match-face-4))))
 '(which-key-key-face ((t (:inherit font-lock-variable-name-face))))
 '(which-func ((t (:inherit font-lock-function-name-face :weight bold))))
 '(which-key-group-description-face ((t (:foreground "#c84053"))))
 '(which-key-command-description-face ((t (:foreground "#4d699b"))))
 '(which-key-local-map-description-face ((t (:foreground "#836f4a"))))
 '(which-key-posframe ((t (:background "#c7d7e0"))))
 '(which-key-posframe-border ((t (:inherit which-key-posframe))))
 '(tree-sitter-hl-face:variable ((t (:foreground "#545464"))))
 '(tree-sitter-hl-face:variable.builtin ((t (:foreground "#c84053"))))
 '(tree-sitter-hl-face:variable.parameter ((t (:foreground "#5d57a3"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#FF5D62"))))
 '(tree-sitter-hl-face:string ((t (:foreground "#6f894e"))))
 '(tree-sitter-hl-face:number ((t (:foreground "#b35b79"))))
 '(tree-sitter-hl-face:string.special ((t (:foreground "#836f4a"))))
 '(tree-sitter-hl-face:attribute ((t (:foreground "#cc6d00"))))
 '(tree-sitter-hl-face:constructor ((t (:foreground "#6693bf"))))
 '(tree-sitter-hl-face:operator ((t (:foreground "#836f4a"))))
 '(tree-sitter-hl-face:keyword ((t (:foreground "#624c83"))))
 '(tree-sitter-hl-face:punctuation ((t (:foreground "#4e8ca2"))))
 '(tree-sitter-hl-face:punctuation.delimiter ((t (:inherit tree-sitter-hl-face:punctuation))))
 '(tree-sitter-hl-face:punctuation.bracket ((t (:inhert tree-sitter-hl-face:punctuation))))
 '(tree-sitter-hl-face:punctuation.special ((t (:foreground "#6693bf"))))
 '(tree-sitter-hl-face:comment ((t (:inherit font-lock-comment-face))))
 '(tree-sitter-hl-face:tag ((t (:inhert tree-sitter-hl-face:attribute))))
 '(tree-sitter-hl-face:label ((t (:foreground "#4e8ca2"))))
 '(elfeed-search-feed-face ((t (:foreground "#624c83"))))
 '(elfeed-search-tag-face ((t (:foreground "#5e857a"))))
 '(doom-modeline-battery-critical ((t (:foreground "#e82424"))))
 '(doom-modeline-battery-warning ((t (:foreground "#6e915f"))))
 '(doom-modeline-battery-charging ((t (:foreground "#8a8980"))))
 '(doom-modeline-battery-error ((t (:foreground "#e82424"))))
 '(doom-modeline-battery-normal ((t (:foreground "#624c83"))))
 '(doom-modeline-battery-full ((t (:foreground "#5e857a"))))
 '(doom-modeline-evil-motion-state ((t (:foreground "#4d699b"))))
 '(doom-modeline-evil-emacs-state ((t (:foreground "#6693bf"))))
 '(doom-modeline-evil-insert-state ((t (:foreground "#FF5D62"))))
 '(doom-modeline-evil-normal-state ((t (:foreground "#4d699b"))))
 '(doom-modeline-evil-visual-state ((t (:foreground "#6e915f"))))
 '(doom-modeline-evil-replace-state ((t (:foreground "#e98a00"))))
 '(doom-modeline-evil-operator-state ((t (:foreground "#4d699b"))))
 '(doom-modeline-project-dir ((t (:foreground "#5e857a" :weight bold))))
 '(doom-modeline-buffer-path ((t (:inherit doom-modeline-project-dir))))
 '(doom-modeline-buffer-file ((t (:foreground "#b35b79"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#836f4a"))))
 '(doom-modeline-error ((t (:background "#e82424"))))
 '(doom-modeline-buffer-major-mode ((t (:inherit doom-modeline-buffer-path))))
 '(doom-modeline-info ((t (:foreground "#4d699b"))))
 '(doom-modeline-bar ((t (:background "#624c83" :weight bold))))
 '(doom-modeline-panel ((t (:foreground "#e5ddb0" :background "#836f4a"))))
 '(doom-themes-visual-bell ((t (:background "#d7474b"))))
 '(anzu-match-1 ((t (:foreground "#5e857a" :background "#e5ddb0"))))
 '(anzu-match-2 ((t (:foreground "#836f4a" :background "#e5ddb0"))))
 '(anzu-match-3 ((t (:foreground "#4d699b" :background "#e5ddb0"))))
 '(anzu-mode-line ((t (:foreground "#d5cea3" :background "#4e8ca2"))))
 '(anzu-mode-no-match ((t (:foreground "#545464" :background "#e82424"))))
 '(anzu-replace-to ((t (:foreground "#6693bf" :background "#d7e3d8"))))
 '(anzu-replace-highlight ((t (:foreground "#e82424" :background "#d9a594" :strike-through t))))
 '(company-tooltip ((t (:background "#c7d7e0"))))
 '(company-tooltip-common ((t (:foreground "#de9800"))))
 '(company-tooltip-quick-access ((t (:foreground "#4e8ca2"))))
 '(company-tooltip-scrollbar-thumb ((t (:background "#b5cbd2"))))
 '(company-tooltip-scrollbar-track ((t (:inherit company-tooltip))))
 '(company-tooltip-search ((t (:foreground "#d5cea3" :background "#836f4a" :distant-foreground "#545464"))))
 '(company-tooltip-selection ((t (:background "#9fb5c9" :weight bold))))
 '(company-tooltip-mouse ((t (:foreground "#d5cea3" :background "#d5cea3" :distant-foreground "#545464"))))
 '(company-tooltip-annotation ((t (:foreground "#9fb5c9"))))
 '(company-scrollbar-bg ((t (:inherit tooltip))))
 '(company-scrollbar-fg ((t (:background "#e82424"))))
 '(company-preview ((t (:foreground "#836f4a"))))
 '(company-preview-common ((t (:foreground "#e82424" :weight bold))))
 '(company-preview-search ((t (:inherit company-tooltip-search))))
 '(company-template-field ((t (:inherit match))))
 '(ace-jump-face-background ((t (:foreground "#6693bf"))))
 '(ace-jump-face-foreground ((t (:foreground "#e82424" :background "#d5cea3" :weight bold))))
 '(vertico-multiline ((t (:background "#e82424"))))
 '(vertico-group-title ((t (:foreground "#4d699b" :background "#d7e3d8" :weight bold))))
 '(vertico-group-separator ((t (:inherit vertico-group-title :strike-through t))))
 '(vertico-current ((t (:foreground "#836f4a" :background "#dcd7ba" :weight bold))))
 '(vertico-posframe-border ((t (:background "#f2ecbc"))))
 '(vertico-posframe ((t (:background "#e5ddb0"))))
 '(marginalia-file-priv-no ((t (:background unspecified))))
 '(hydra-face-amaranth ((t (:foreground "#d7474b"))))
 '(hydra-face-blue ((t (:foreground "#6693bf"))))
 '(hydra-face-pink ((t (:foreground "#b35b79"))))
 '(hydra-face-red ((t (:foreground "#e82424"))))
 '(hydra-face-teal ((t (:foreground "#4d699b"))))
 '(centaur-tabs-active-bar-face ((t (:foreground "#545464" :background "#6693bf"))))
 '(centaur-tabs-selected ((t (:foreground "#545464" :background "#f2ecbc" :weight bold))))
 '(centaur-tabs-selected-modified ((t (:foreground "#545464" :background "#f2ecbc"))))
 '(centaur-tabs-modified-marker-selected ((t (:foreground "#de9800" :background "#f2ecbc"))))
 '(centaur-tabs-close-selected ((t (:inherit centaur-tabs-selected))))
 '(centaur-tabs-unselected ((t (:foreground "#e7dba0" :background "#d5cea3"))))
 '(centaur-tabs-default ((t (:inherit centaur-tabs-unselected))))
 '(centaur-tabs-unselected-modified ((t (:foreground "#e82424" :background "#d5cea3"))))
 '(centaur-tabs-modified-marker-unselected ((t (:inherit centaur-tabs-unselected))))
 '(centaur-tabs-close-unselected ((t (:inherit centaur-tabs-unselected))))
 '(centaur-tabs-close-mouse-face ((t (:foreground "#e82424" :background unspecified))))
 '(centaur-tabs-default ((t (:background "#e98a00"))))
 '(centaur-tabs-name-mouse-face ((t (:foreground "#6693bf" :weight bold))))
 '(git-gutter:added ((t (:foreground "#6e915f"))))
 '(git-gutter:deleted ((t (:foreground "#6693bf"))))
 '(git-gutter:modified ((t (:foreground "#6693bf"))))
 '(diff-hl-margin-change ((t (:foreground "#6693bf" :background "#d7e3d8"))))
 '(diff-hl-margin-delete ((t (:foreground "#e82424" :background "#d9a594"))))
 '(diff-hl-margin-insert ((t (:foreground "#a09cac" :background "#d7e3d8"))))
 '(flycheck-posframe-background-face ((t (:background "#d5cea3"))))
 '(flycheck-posframe-face ((t (:inherit flycheck-posframe-background-face))))
 '(flycheck-posframe-info-face ((t (:foreground "#6e915f" :background "#d5cea3"))))
 '(flycheck-posframe-warning-face ((t (:foreground "#4d699b" :background "#d5cea3"))))
 '(flycheck-posframe-error-face ((t (:foreground "#e82424" :background "#d5cea3"))))
 '(flycheck-fringe-warning ((t (:foreground "#4d699b"))))
 '(flycheck-fringe-error ((t (:foreground "#e82424"))))
 '(flycheck-fringe-info ((t (:foreground "#6e915f"))))
 '(flycheck-error-list-warning ((t (:foreground "#e98a00" :weight bold))))
 '(flycheck-error-list-error ((t (:foreground "#e82424" :weight bold))))
 '(flycheck-error-list-info ((t (:foreground "#5e857a" :weight bold))))
 '(flycheck-inline-error ((t (:foreground "#e82424" :background "#d9a594" :weight bold :height 138))))
 '(flycheck-inline-info ((t (:foreground "#4d699b" :background "#d7e3d8" :weight bold :height 138))))
 '(flycheck-inline-warning ((t (:foreground "#f9d791" :background "#836f4a" :weight bold :height 138))))
 '(dashboard-heading ((t (:foreground "#4e8ca2" :weight bold))))
 '(dashboard-banner-logo-title ((t (:weight bold :height 200))))
 '(dashboard-no-items-face ((t (:foreground "#e7dba0"))))
 '(popup-face ((t (:inherit tooltip))))
 '(popup-selection-face ((t (:inherit tooltip))))
 '(popup-tip-face ((t (:inherit tooltip))))
 '(orderless-match-face-0 ((t (:foreground "#6f894e"))))
 '(orderless-match-face-1 ((t (:foreground "#b35b79"))))
 '(orderless-match-face-2 ((t (:foreground "#4d699b"))))
 '(orderless-match-face-3 ((t (:foreground "#597b75"))))
 '(magit-blame-culprit ((t (:background "#e7dba0" :foreground "#77713f"))))
 '(magit-blame-date ((t (:background "#e7dba0" :foreground "#6f894e"))))
 '(magit-blame-hash ((t (:background "#e7dba0" :foreground "#4d699b"))))
 '(magit-blame-header ((t (:background "#e7dba0" :foreground "#6f894e"))))
 '(magit-blame-heading ((t (:background "#e7dba0" :foreground "#6f894e"))))
 '(magit-blame-name ((t (:background "#e7dba0" :foreground "#77713f"))))
 '(magit-blame-sha1 ((t (:background "#e7dba0" :foreground "#4d699b"))))
 '(magit-blame-subject ((t (:background "#e7dba0" :foreground "#77713f"))))
 '(magit-blame-summary ((t (:background "#e7dba0" :foreground "#77713f" :extend t))))
 '(magit-blame-time ((t (:background "#e7dba0" :foreground "#6f894e"))))
 '(magit-branch ((t (:foreground "#cc6d00" :inherit bold))))
 '(magit-branch-current ((t (:background "#e7dba0" :foreground "#4d699b" :inherit bold :box t))))
 '(magit-branch-local ((t (:background "#e7dba0" :foreground "#4d699b" :inherit bold))))
 '(magit-branch-remote ((t (:background "#e4d794" :foreground "#4d699b" :inherit bold))))
 '(magit-diff-context-highlight ((t (:background "#e5ddb0" :foreground "#545464" :extend t))))
 '(magit-diff-hunk-heading ((t (:background "#c7d7e0" :foreground "#43436c" :extend t))))
 '(magit-diff-hunk-heading-highlight ((t (:background "#9fb5c9" :foreground unspecified :extend t))))
 '(magit-hash ((t (:foreground nil))))
 '(magit-hunk-heading ((t (:background "#d5cea3" :extend t))))
 '(magit-hunk-heading-highlight ((t (:background "#e4d794" :extend t))))
 '(magit-item-highlight ((t (:background "#e4d794" :extend t))))
 '(magit-log-author ((t (:foreground "#4d699b"))))
 '(magit-log-head-label-head ((t (:background "#77713f" :foreground "#f2ecbc" :inherit bold))))
 '(magit-log-head-label-local ((t (:background "#624c83" :foreground "#f2ecbc" :inherit bold))))
 '(magit-log-head-label-remote ((t (:background "#6f894e" :foreground "#f2ecbc" :inherit bold))))
 '(magit-log-head-label-tags ((t (:background "#b35b79" :foreground "#f2ecbc" :inherit bold))))
 '(magit-log-head-label-wip ((t (:background "#597b75" :foreground "#f2ecbc" :inherit bold))))
 '(magit-log-sha1 ((t (:foreground "#6f894e"))))
 '(magit-process-ng ((t (:foreground "#e98a00" :inherit bold))))
 '(magit-process-ok ((t (:foreground "#4d699b" :inherit bold))))
 '(magit-reflog-amend ((t (:foreground "#b35b79"))))
 '(magit-reflog-checkout ((t (:foreground "#4d699b"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#6f894e"))))
 '(magit-reflog-commit ((t (:foreground "#6f894e"))))
 '(magit-reflog-merge ((t (:foreground "#6f894e"))))
 '(magit-reflog-other ((t (:foreground "#597b75"))))
 '(magit-reflog-rebase ((t (:foreground "#b35b79"))))
 '(magit-reflog-remote ((t (:foreground "#597b75"))))
 '(magit-reflog-reset ((t (:foreground "#c84053"))))
 '(magit-section-heading ((t (:foreground "#624c83" :inherit bold :extend t))))
 '(magit-section-highlight ((t (:background "#dcd5ac" :extend t))))
 '(magit-section-title ((t (:background "#f2ecbc" :foreground "#624c83" :inherit bold))))
 '(dired-subtree-depth-1-face ((t (:background "#f2ecbc"))))
 '(dired-subtree-depth-2-face ((t (:background "#f2ecbc"))))
 '(dired-subtree-depth-3-face ((t (:background "#f2ecbc"))))
 '(dired-subtree-depth-4-face ((t (:background "#f2ecbc"))))
 '(dired-subtree-depth-5-face ((t (:background "#f2ecbc"))))
 '(dired-subtree-depth-6-face ((t (:background "#f2ecbc"))))
 '(corfu-default ((t (:background "#e5ddb0"))))
 '(corfu-current ((t (:background "#e4d794" :foreground nil))))
 '(corfu-deprecated ((t (:inherit nil))))
 '(corfu-bar ((t (:background nil :inherit tooltip))))
 '(corfu-border ((t (:background "#f2ecbc"))))
 '(wgrep-face ((t (:foreground "#6f894e"))))
 '(wgrep-delete-face ((t (:foreground "#c84053"))))
 '(wgrep-reject-face ((t (:foreground "#c84053"))))
 '(wgrep-file-face ((t (:foreground "#6f894e"))))
 '(wgrep-done-face ((t (:foreground "#4d699b"))))
 '(diredfl-autofile-name ((t (:foreground "#b5cbd2"))))
 '(diredfl-compressed-file-name ((t (:foreground "#f9d791"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#de9800"))))
 '(diredfl-date-time ((t (:foreground "#624c83"))))
 '(diredfl-deletion ((t (:background "#e98a00" :foreground "#e82424"))))
 '(diredfl-deletion-file-name ((t (:foreground "#e82424"))))
 '(diredfl-dir-heading ((t (:foreground "#6693bf"))))
 '(diredfl-dir-name ((t (:foreground "#624c83"))))
 '(diredfl-dir-priv ((t (:foreground "#624c83"))))
 '(diredfl-exec-priv ((t (:foreground "#4d699b"))))
 '(diredfl-executable-tag ((t (:foreground "#c84053"))))
 '(diredfl-file-name ((t (:foreground "#545464"))))
 '(diredfl-file-suffix ((t (:foreground "#b35b79"))))
 '(diredfl-flag-mark ((t (:foreground "#77713f"))))
 '(diredfl-flag-mark-line ((t (:foreground "#6693bf"))))
 '(diredfl-ignored-file-name ((t (:foreground "#597b75"))))
 '(diredfl-link-priv ((t (:foreground "#cc6d00"))))
 '(diredfl-no-priv ((t (:foreground "#545464"))))
 '(diredfl-number ((t (:foreground "#cc6d00"))))
 '(diredfl-other-priv ((t (:foreground "#77713f"))))
 '(diredfl-rare-priv ((t (:foreground "#b35b79"))))
 '(diredfl-read-priv ((t (:foreground "#597b75"))))
 '(diredfl-symlink ((t (:foreground "#6693bf"))))
 '(diredfl-tagged-autofile-name ((t (:foreground "#6f894e"))))
 '(diredfl-write-priv ((t (:foreground "#545464"))))
 '(markdown-header-delimiter-face ((t (:foreground "#a09cac" :background "#f2ecbc"))))
 '(markdown-markup-face ((t (:foreground "#a09cac" :background "#f2ecbc"))))
 '(whitespace-tab ((t (:foreground "#8a8980" :background "#f2ecbc"))))
 '(default ((t (:foreground "#545464" :background "#f2ecbc")))))

(provide-theme 'kanagawa-lotus)
