(deftheme kanagawa-wave
  "The Kanagawa wave theme")

(custom-theme-set-faces
 'kanagawa-wave
 '(button ((t (:underline t))))
 '(link ((t :foreground "#7FB4CA" :underline t :weight bold)))
 '(link-visited ((t :foreground "#7E9CD8" :underline t :weight normal)))
 '(cursor ((t (:foreground "#1F1F28" :background "#DCD7BA"))))
 '(widget-field ((t (:foreground "#DCD7BA" :background "#2A2A37"))))
 '(escape-glyph ((t (:foreground "#938AA9" :weight bold))))
 '(fringe ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(header-line ((t (:foreground "#DCD7BA" :background "#2A2A37" :extend t))))
 '(highlight ((t (:foreground "#DCD7BA" :background "#181820" :weight bold))))
 '(success ((t (:foreground "#98BB6C" :weight bold))))
 '(warning ((t (:foreground "#FF9E3B" :weight bold))))
 '(tooltip ((t (:foreground "#DCD7BA" :background "#223249"))))
 '(menu ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(region ((t (:background "#223249"))))
 '(separator-line ((t (:background "#16161D"))))
 '(shadow ((t (:inherit separator-line))))
 '(window-border ((t (:background "#1F1F28"))))
 '(window-divider ((t (:foreground "#1a1a22"))))
 '(vertical-border ((t (:foreground "#1a1a22"))))
 '(font-lock-builtin-face ((t (:foreground "#E46876"))))
 '(font-lock-comment-face ((t (:foreground "#727169"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#727169"))))
 '(font-lock-bracket-face ((t (:foreground "#9CABCA"))))
 '(font-lock-delimiter-face ((t (:foreground "#9CABCA"))))
 '(font-lock-constant-face ((t (:foreground "#FFA066"))))
 '(font-lock-doc-face ((t (:foreground "#98BB6C"))))
 '(font-lock-function-name-face ((t (:foreground "#7E9CD8"))))
 '(font-lock-keyword-face ((t (:foreground "#957FB8" :weight bold))))
 '(font-lock-operator-face ((t (:foreground "#C0A36E"))))
 '(font-lock-negation-char-face ((t (:inherit font-lock-keyword-face))))
 '(font-lock-preprocessor-face ((t (:foreground "#E46876"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#C0A36E" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#C0A36E" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#98BB6C"))))
 '(font-lock-number-face ((t (:foreground "#D27E99"))))
 '(font-lock-type-face ((t (:foreground "#7AA89F"))))
 '(font-lock-variable-name-face ((t (:foreground nil))))
 '(font-lock-property-use-face ((t (:foreground "#E6C384"))))
 '(font-lock-warning-face ((t (:foreground "#FF9E3B"))))
 '(c-annotation-face ((t (:inherit font-lock-constant-face))))
 '(line-number ((t (:background "#1F1F28" :foreground "#54546D"))))
 '(line-number-current-line ((t (:background "#1F1F28" :foreground "#FFA066"))))
 '(ansi-color-black ((t (:foreground "#16161D"))))
 '(ansi-color-red ((t (:foreground "#C34043"))))
 '(ansi-color-green ((t (:foreground "#76946A"))))
 '(ansi-color-yellow ((t (:foreground "#C0A36E"))))
 '(ansi-color-blue ((t (:foreground "#7E9CD8"))))
 '(ansi-color-magenta ((t (:foreground "#957FB8"))))
 '(ansi-color-cyan ((t (:foreground "#6A9589"))))
 '(ansi-color-white ((t (:foreground "#C8C093"))))
 '(ansi-color-bright-black ((t (:foreground "#727169"))))
 '(ansi-color-bright-red ((t (:foreground "#E82424"))))
 '(ansi-color-bright-green ((t (:foreground "#98BB6C"))))
 '(ansi-color-bright-yellow ((t (:foreground "#E6C384"))))
 '(ansi-color-bright-blue ((t (:foreground "#7FB4CA"))))
 '(ansi-color-bright-magenta ((t (:foreground "#938AA9"))))
 '(ansi-color-bright-cyan ((t (:foreground "#7AA89F"))))
 '(ansi-color-bright-white ((t (:foreground "#DCD7BA"))))
 '(isearch ((t (:foreground "#223249" :background "#FF9E3B"))))
 '(isearch-fail ((t (:foreground "#DCD7BA" :background "#E82424"))))
 '(lazy-highlight ((t (:foreground "#DCD7BA" :background "#2D4F67"))))
 '(minibuffer-prompt ((t (:foreground "#DCD7BA" :weight bold))))
 '(mode-line ((t (:foreground "#C8C093" :background "#16161D"))))
 '(mode-line-inactive ((t (:foreground "#54546D" :background "#16161D"))))
 '(hl-line ((t (:background "#363646"))))
 '(message-header-name ((t (:foreground "#2A2A37"))))
 '(message-header-other ((t (:foreground "#FFA066"))))
 '(message-header-subject ((t (:foreground "#E6C384"))))
 '(message-header-to ((t (:foreground "#C8C093"))))
 '(message-header-cc ((t (:foreground "#7AA89F"))))
 '(message-header-xheader ((t (:foreground "#C8C093"))))
 '(erc-action-face ((t (:inherit erc-default-face))))
 '(erc-bold-face ((t (:weight bold))))
 '(erc-current-nick-face ((t (:foreground "#FFA066" :weight bold))))
 '(erc-direct-msg-face ((t (:inherit erc-default-face))))
 '(erc-error-face ((t (:foreground "#FF9E3B"))))
 '(erc-fool-face ((t (:inherit erc-default-face))))
 '(erc-input-face ((t (:foreground "#DCD7BA"))))
 '(erc-keyword-face ((t (:inherit font-lock-keyword-face))))
 '(erc-nick-default-face ((t (:foreground "#7FB4CA" :weight bold))))
 '(erc-my-nick-face ((t (:foreground "#C34043"))))
 '(erc-notice-face ((t (:foreground "#98BB6C"))))
 '(erc-prompt-face ((t (:inherit minibuffer-prompt))))
 '(erc-timestamp-face ((t (:inherit font-lock-keyword-face))))
 '(erc-underline-face ((t (:underline t))))
 '(term ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(term-color-black ((t (:foreground "#16161D" :background "#16161D"))))
 '(term-color-red ((t (:foreground "#C34043" :background "#C34043"))))
 '(term-color-green ((t (:foreground "#76946A" :background "#76946A"))))
 '(term-color-yellow ((t (:foreground "#C0A36E" :background "#C0A36E"))))
 '(term-color-blue ((t (:foreground "#7E9CD8" :background "#7E9CD8"))))
 '(term-color-magenta ((t (:foreground "#957FB8" :background "#957FB8"))))
 '(term-color-cyan ((t (:foreground "#6A9589" :background "#6A9589"))))
 '(term-color-white ((t (:foreground "#C8C093" :background "#C8C093"))))
 '(org-done ((t (:foreground "#658594"))))
 '(org-code ((t (:background "#16161D"))))
 '(org-meta-line ((t (:foreground "#98BB6C" :background "#2B3328"))))
 '(org-block ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(org-block-begin-line ((t (:foreground "#7FB4CA" :background "#252535"))))
 '(org-block-end-line ((t (:foreground "#FF5D62" :background "#43242B"))))
 '(org-headline-done ((t (:foreground "#658594" :strike-through t))))
 '(org-todo ((t (:foreground "#FFA066" :weight bold))))
 '(org-headline-todo ((t (:foreground "#1a1a22"))))
 '(org-upcoming-deadline ((t (:foreground "#FFA066"))))
 '(org-footnote ((t (:foreground "#7AA89F"))))
 '(org-indent ((t (:foreground "#1F1F28" :background "#1F1F28"))))
 '(org-hide ((t (:inherit org-indent))))
 '(org-date ((t (:foreground "#2D4F67"))))
 '(org-ellipsis ((t (:foreground "#2D4F67" :weight bold))))
 '(org-level-1 ((t (:foreground "#957FB8" :height 1.3 :weight bold))))
 '(org-level-2 ((t (:foreground "#7E9CD8" :height 1.2 :weight bold))))
 '(org-level-3 ((t (:foreground "#7AA89F" :height 1.1))))
 '(org-level-4 ((t (:foreground "#98BB6C"))))
 '(org-level-5 ((t (:foreground "#E6C384"))))
 '(org-level-6 ((t (:foreground "#FFA066"))))
 '(org-level-7 ((t (:foreground "#C34043"))))
 '(org-level-8 ((t (:foreground "#938AA9"))))
 '(org-priority ((t (:foreground "#FF5D62" :weight bold))))
 '(show-paren-match ((t (:foreground "#FF9E3B" :weight bold))))
 '(show-paren-match-expression ((t (:inherit show-paren-match))))
 '(show-paren-mismatch ((t (:foreground "#727169" :weight bold))))
 '(tab-line ((t (:background "#16161D"))))
 '(comint-highlight-prompt ((t (:background "#9CABCA" :foreground "#181820"))))
 '(completions-annotations ((t (:background unspecified :foreground "#658594"))))
 '(dired-directory ((t (:foreground "#957FB8" :inherit bold))))
 '(dired-flagged ((t (:foreground "#C34043"))))
 '(dired-header ((t (:foreground "#C8C093" :weight bold))))
 '(dired-ignored ((t (:inherit shadow))))
 '(dired-mark ((t (:foreground "#E46876" :inherit bold))))
 '(dired-marked ((t (:foreground "#957FB8" :inherit bold))))
 '(dired-perm-write ((t (:foreground "#DCD7BA" :underline t))))
 '(dired-symlink ((t (:foreground "#6A9589"))))
 '(dired-warning ((t (:foreground "#FF9E3B"))))
 '(highlight-indent-guides-character-face ((t (:foreground "#1F1F28"))))
 '(highlight-indent-guides-stack-character-face ((t (:foreground "#1F1F28"))))
 '(highlight-indent-guides-stack-odd-face ((t (:foreground "#1F1F28"))))
 '(highlight-indent-guides-stack-even-face ((t (:foreground "#54546D"))))
 '(highlight-indent-guides-stack-character-face ((t (:foreground "#1F1F28"))))
 '(highlight-indent-guides-even-face ((t (:foreground "#16161D"))))
 '(highlight-indent-guides-odd-face ((t (:foreground "#54546D"))))
 '(ivy-current-match ((t (:foreground "#16161D" :background "#7E9CD8" :weight bold))))
 '(ivy-action ((t (:foreground "#DCD7BA"))))
 '(ivy-grep-line-number ((t (:foreground "#98BB6C"))))
 '(ivy-minibuffer-match-face-1 ((t (:foreground "#E46876"))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit ivy-grep-line-number))))
 '(ivy-minibuffer-match-highlight ((t (:foreground "#7E9CD8"))))
 '(ivy-grep-info ((t (:foreground "#7E9CD8"))))
 '(ivy-grep-line-number ((t (:foreground "#9CABCA"))))
 '(ivy-confirm-face ((t (:foreground "#7AA89F"))))
 '(ivy-posframe ((t (:background "#1a1a22"))))
 '(ivy-posframe-border ((t (:background "#1F1F28"))))
 '(helm-bookmark-directory ((t (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((t (:foreground "#957FB8"))))
 '(helm-bookmark-gnus ((t (:foreground "#957FB8"))))
 '(helm-bookmark-info ((t (:foreground "#957FB8"))))
 '(helm-bookmark-man ((t (:foreground "#957FB8"))))
 '(helm-bookmark-w3m ((t (:foreground "#957FB8"))))
 '(helm-buffer-directory ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(helm-buffer-file ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(helm-buffer-not-saved ((t (:foreground "#957FB8" :background "#1F1F28"))))
 '(helm-buffer-process ((t (:foreground "#957FB8" :background "#1F1F28"))))
 '(helm-buffer-saved-out ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(helm-buffer-size ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(helm-candidate-number ((t (:background "#1F1F28" :foreground "#957FB8" :inherit bold))))
 '(helm-ff-directory ((t (:foreground "#957FB8" :background "#1F1F28" :inherit bold))))
 '(helm-ff-dotted-directory ((t (:foreground "#957FB8" :background "#1F1F28" :inherit bold))))
 '(helm-ff-dotted-symlink-directory ((t (:foreground "#6A9589" :background "#1F1F28" :inherit bold))))
 '(helm-ff-executable ((t (:foreground "#98BB6C" :background "#1F1F28" :weight normal))))
 '(helm-ff-file ((t (:foreground "#DCD7BA" :background "#1F1F28" :weight normal))))
 '(helm-ff-invalid-symlink ((t (:foreground "#C34043" :background "#1F1F28" :inherit bold))))
 '(helm-ff-prefix ((t (:foreground "#1F1F28" :background "#957FB8" :weight normal))))
 '(helm-ff-symlink ((t (:foreground "#6A9589" :background "#1F1F28" :inherit bold))))
 '(helm-grep-cmd-line ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(helm-grep-file ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(helm-grep-finish ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(helm-grep-lineno ((t (:foreground "#7AA89F" :background "#1F1F28" :inherit bold))))
 '(helm-grep-match ((t (:foreground unspecified :background unspecified :inherit helm-match))))
 '(helm-header ((t (:foreground "#DCD7BA" :background "#1F1F28" :underline nil :box nil))))
 '(helm-match ((t (:foreground "#76946A"))))
 '(helm-match-item ((t (:foreground "#76946A"))))
 '(helm-moccur-buffer ((t (:foreground nil :background "#1F1F28"))))
 '(helm-selection ((t (:background "#223249"))))
 '(helm-selection-line ((t (:background "#1a1a22"))))
 '(helm-separator ((t (:foreground "#957FB8" :background "#1F1F28"))))
 '(helm-source-header ((t (:background "#957FB8" :foreground "#1F1F28" :inherit bold))))
 '(helm-time-zone-current ((t (:foreground "#957FB8" :background "#1F1F28"))))
 '(helm-time-zone-home ((t (:foreground "#957FB8" :background "#1F1F28"))))
 '(helm-visible-mark ((t (:foreground "#957FB8" :background "#16161D"))))
 '(helm-swoop-target-line-block-face ((t (:foreground "#DCD7BA" :background "#181820"))))
 '(helm-swoop-target-line-face ((t (:background "#181820"))))
 '(helm-swoop-target-word-face ((t (:background "#181820" :foreground "#FF9E3B"))))
 '(treemacs-directory-collapsed-face ((t (:foreground "#DCD7BA"))))
 '(treemacs-directory-face ((t (:inherit treemacs-directory-collapsed-face))))
 '(treemacs-file-face ((t (:inherit treemacs-directory-face))))
 '(treemacs-git-added-face ((t (:foreground "#FFA066"))))
 '(treemacs-git-renamed-face ((t (:inherit treemacs-file-face))))
 '(treemacs-git-ignored-face ((t (:foreground "#2A2A37"))))
 '(treemacs-git-unmodified-face ((t (:inhert treemacs-git-renamed-face))))
 '(treemacs-git-renamed-face ((t (:inhert treemacs-git-unmodified-face))))
 '(treemacs-git-modified-face ((t (:foreground "#98BB6C"))))
 '(lsp-headerline-breadcrumb-path-error-face ((t (:underline (:color "#98BB6C" :style wave) :foreground "#2A2A37" :background "#16161D"))))
 '(lsp-headerline-breadcrumb-path-face ((t (:background "#16161D"))))
 '(lsp-headerline-breadcrumb-path-hint-face ((t (:foreground "#6A9589"))))
 '(lsp-headerline-breadcrumb-path-info-face ((t (:foreground "#658594"))))
 '(lsp-headerline-breadcrumb-separator-face ((t (:inherit lsp-headerline-breadcrumb-path-face))))
 '(lsp-headerline-breadcrumb-symbols-face ((t (:inherit lsp-headerline-breadcrumb-path-face))))
 '(lsp-headerline-breadcrumb-project-prefix-face ((t (:inherit lsp-headerline-breadcrumb-path-face))))
 '(lsp-headerline-breadcrumb-symbols-error-face ((t (:foreground "#FF5D62"))))
 '(lsp-ui-doc-background ((t (:foreground "#FF5D62" :background "#16161D"))))
 '(lsp-ui-doc-header ((t (:inherit lsp-ui-doc-background))))
 '(lsp-ui-doc-border ((t (:background unspecified :foreground unspecified))))
 '(lsp-ui-peek-peek ((t (:background "#181820"))))
 '(lsp-ui-peek-list ((t (:background "#16161D"))))
 '(lsp-ui-peek-filename ((t (:foreground "#7E9CD8"))))
 '(lsp-ui-peek-line-number ((t (:foreground "#54546D"))))
 '(lsp-ui-peek-highlight ((t (:foreground "#DCD7BA" :background "#2D4F67" :box (:line-width -1 :color "#658594")))))
 '(lsp-ui-peek-header ((t (:foreground "#DCD7BA" :background "#223249" :bold t))))
 '(lsp-ui-peek-footer ((t (:inherit lsp-ui-peek-header))))
 '(lsp-ui-peek-selection ((t (:foreground "#DCD7BA" :background "#2D4F67"))))
 '(lsp-ui-sideline-code-action ((t (:foreground "#E6C384"))))
 '(lsp-ui-sideline-current-symbol ((t (:foreground "#7FB4CA"))))
 '(lsp-ui-sideline-symbol ((t (:foreground "#658594"))))
 '(rainbow-delimiters-mismatched-face ((t (:foreground "#FF5D62"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#7AA89F"))))
 '(rainbow-delimiters-base-error-face ((t (:foreground "#FF5D62"))))
 '(rainbow-delimiters-base-face ((t (:foreground "#2A2A37"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#9CABCA"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#658594"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#938AA9"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#98BB6C"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#7AA89F"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#E6C384"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#FF5D62"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#7E9CD8"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#9CABCA"))))
 '(swiper-line-face ((t (:foreground "#E6C384"))))
 '(swiper-background-match-face-1 ((t (:foreground "#16161D" :background "#FFA066"))))
 '(swiper-background-match-face-2 ((t (:foreground "#16161D" :background "#7E9CD8"))))
 '(swiper-background-match-face-3 ((t (:foreground "#16161D" :background "#C0A36E"))))
 '(swiper-background-match-face-4 ((t (:foreground "#16161D" :background "#FF5D62"))))
 '(swiper-match-face-1 ((t (:inherit swiper-background-match-face-1))))
 '(swiper-match-face-2 ((t (:inherit swiper-background-match-face-2))))
 '(swiper-match-face-3 ((t (:inherit swiper-background-match-face-3))))
 '(swiper-match-face-4 ((t (:inherit swiper-background-match-face-4))))
 '(which-key-key-face ((t (:inherit font-lock-variable-name-face))))
 '(which-func ((t (:inherit font-lock-function-name-face :weight bold))))
 '(which-key-group-description-face ((t (:foreground "#E46876"))))
 '(which-key-command-description-face ((t (:foreground "#7E9CD8"))))
 '(which-key-local-map-description-face ((t (:foreground "#E6C384"))))
 '(which-key-posframe ((t (:background "#223249"))))
 '(which-key-posframe-border ((t (:inherit which-key-posframe))))
 '(tree-sitter-hl-face:variable ((t (:foreground "#DCD7BA"))))
 '(tree-sitter-hl-face:variable.builtin ((t (:foreground "#E46876"))))
 '(tree-sitter-hl-face:variable.parameter ((t (:foreground "#b8b4d0"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#FF5D62"))))
 '(tree-sitter-hl-face:string ((t (:foreground "#98BB6C"))))
 '(tree-sitter-hl-face:number ((t (:foreground "#D27E99"))))
 '(tree-sitter-hl-face:string.special ((t (:foreground "#C0A36E"))))
 '(tree-sitter-hl-face:attribute ((t (:foreground "#FFA066"))))
 '(tree-sitter-hl-face:constructor ((t (:foreground "#7FB4CA"))))
 '(tree-sitter-hl-face:operator ((t (:foreground "#C0A36E"))))
 '(tree-sitter-hl-face:keyword ((t (:foreground "#957FB8"))))
 '(tree-sitter-hl-face:punctuation ((t (:foreground "#9CABCA"))))
 '(tree-sitter-hl-face:punctuation.delimiter ((t (:inherit tree-sitter-hl-face:punctuation))))
 '(tree-sitter-hl-face:punctuation.bracket ((t (:inhert tree-sitter-hl-face:punctuation))))
 '(tree-sitter-hl-face:punctuation.special ((t (:foreground "#7FB4CA"))))
 '(tree-sitter-hl-face:comment ((t (:inherit font-lock-comment-face))))
 '(tree-sitter-hl-face:tag ((t (:inhert tree-sitter-hl-face:attribute))))
 '(tree-sitter-hl-face:label ((t (:foreground "#9CABCA"))))
 '(elfeed-search-feed-face ((t (:foreground "#938AA9"))))
 '(elfeed-search-tag-face ((t (:foreground "#7AA89F"))))
 '(doom-modeline-battery-critical ((t (:foreground "#FF5D62"))))
 '(doom-modeline-battery-warning ((t (:foreground "#98BB6C"))))
 '(doom-modeline-battery-charging ((t (:foreground "#727169"))))
 '(doom-modeline-battery-error ((t (:foreground "#FF5D62"))))
 '(doom-modeline-battery-normal ((t (:foreground "#938AA9"))))
 '(doom-modeline-battery-full ((t (:foreground "#7AA89F"))))
 '(doom-modeline-evil-motion-state ((t (:foreground "#7E9CD8"))))
 '(doom-modeline-evil-emacs-state ((t (:foreground "#7FB4CA"))))
 '(doom-modeline-evil-insert-state ((t (:foreground "#FF5D62"))))
 '(doom-modeline-evil-normal-state ((t (:foreground "#7E9CD8"))))
 '(doom-modeline-evil-visual-state ((t (:foreground "#98BB6C"))))
 '(doom-modeline-evil-replace-state ((t (:foreground "#FF9E3B"))))
 '(doom-modeline-evil-operator-state ((t (:foreground "#7E9CD8"))))
 '(doom-modeline-project-dir ((t (:foreground "#7AA89F" :weight bold))))
 '(doom-modeline-buffer-path ((t (:inherit doom-modeline-project-dir))))
 '(doom-modeline-buffer-file ((t (:foreground "#957FB8"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#E6C384"))))
 '(doom-modeline-error ((t (:background "#FF5D62"))))
 '(doom-modeline-buffer-major-mode ((t (:inherit doom-modeline-buffer-path))))
 '(doom-modeline-info ((t (:foreground "#7E9CD8"))))
 '(doom-modeline-bar ((t (:background "#938AA9" :weight bold))))
 '(doom-modeline-panel ((t (:foreground "#1a1a22" :background "#C0A36E"))))
 '(doom-themes-visual-bell ((t (:background "#C34043"))))
 '(anzu-match-1 ((t (:foreground "#7AA89F" :background "#1a1a22"))))
 '(anzu-match-2 ((t (:foreground "#E6C384" :background "#1a1a22"))))
 '(anzu-match-3 ((t (:foreground "#7E9CD8" :background "#1a1a22"))))
 '(anzu-mode-line ((t (:foreground "#16161D" :background "#9CABCA"))))
 '(anzu-mode-no-match ((t (:foreground "#DCD7BA" :background "#FF5D62"))))
 '(anzu-replace-to ((t (:foreground "#7FB4CA" :background "#252535"))))
 '(anzu-replace-highlight ((t (:foreground "#FF5D62" :background "#43242B" :strike-through t))))
 '(company-tooltip ((t (:background "#223249"))))
 '(company-tooltip-common ((t (:foreground "#DCA561"))))
 '(company-tooltip-quick-access ((t (:foreground "#9CABCA"))))
 '(company-tooltip-scrollbar-thumb ((t (:background "#2D4F67"))))
 '(company-tooltip-scrollbar-track ((t (:inherit company-tooltip))))
 '(company-tooltip-search ((t (:foreground "#16161D" :background "#E6C384" :distant-foreground "#DCD7BA"))))
 '(company-tooltip-selection ((t (:background "#2D4F67" :weight bold))))
 '(company-tooltip-mouse ((t (:foreground "#16161D" :background "#16161D" :distant-foreground "#DCD7BA"))))
 '(company-tooltip-annotation ((t (:foreground "#2D4F67"))))
 '(company-scrollbar-bg ((t (:inherit tooltip))))
 '(company-scrollbar-fg ((t (:background "#FF5D62"))))
 '(company-preview ((t (:foreground "#E6C384"))))
 '(company-preview-common ((t (:foreground "#FF5D62" :weight bold))))
 '(company-preview-search ((t (:inherit company-tooltip-search))))
 '(company-template-field ((t (:inherit match))))
 '(ace-jump-face-background ((t (:foreground "#7FB4CA"))))
 '(ace-jump-face-foreground ((t (:foreground "#FF5D62" :background "#16161D" :weight bold))))
 '(vertico-multiline ((t (:background "#E82424"))))
 '(vertico-group-title ((t (:foreground "#7E9CD8" :background "#252535" :weight bold))))
 '(vertico-group-separator ((t (:inherit vertico-group-title :strike-through t))))
 '(vertico-current ((t (:foreground "#E6C384" :background "#223249" :weight bold))))
 '(vertico-posframe-border ((t (:background "#1F1F28"))))
 '(vertico-posframe ((t (:background "#1a1a22"))))
 '(marginalia-file-priv-no ((t (:background unspecified))))
 '(hydra-face-amaranth ((t (:foreground "#C34043"))))
 '(hydra-face-blue ((t (:foreground "#7FB4CA"))))
 '(hydra-face-pink ((t (:foreground "#D27E99"))))
 '(hydra-face-red ((t (:foreground "#FF5D62"))))
 '(hydra-face-teal ((t (:foreground "#7E9CD8"))))
 '(centaur-tabs-active-bar-face ((t (:foreground "#DCD7BA" :background "#7FB4CA"))))
 '(centaur-tabs-selected ((t (:foreground "#DCD7BA" :background "#1F1F28" :weight bold))))
 '(centaur-tabs-selected-modified ((t (:foreground "#DCD7BA" :background "#1F1F28"))))
 '(centaur-tabs-modified-marker-selected ((t (:foreground "#DCA561" :background "#1F1F28"))))
 '(centaur-tabs-close-selected ((t (:inherit centaur-tabs-selected))))
 '(centaur-tabs-unselected ((t (:foreground "#2A2A37" :background "#16161D"))))
 '(centaur-tabs-default ((t (:inherit centaur-tabs-unselected))))
 '(centaur-tabs-unselected-modified ((t (:foreground "#FF5D62" :background "#16161D"))))
 '(centaur-tabs-modified-marker-unselected ((t (:inherit centaur-tabs-unselected))))
 '(centaur-tabs-close-unselected ((t (:inherit centaur-tabs-unselected))))
 '(centaur-tabs-close-mouse-face ((t (:foreground "#FF5D62" :background unspecified))))
 '(centaur-tabs-default ((t (:background "#FF9E3B"))))
 '(centaur-tabs-name-mouse-face ((t (:foreground "#7FB4CA" :weight bold))))
 '(git-gutter:added ((t (:foreground "#76946A"))))
 '(git-gutter:deleted ((t (:foreground "#7FB4CA"))))
 '(git-gutter:modified ((t (:foreground "#7FB4CA"))))
 '(diff-hl-margin-change ((t (:foreground "#7FB4CA" :background "#252535"))))
 '(diff-hl-margin-delete ((t (:foreground "#FF5D62" :background "#43242B"))))
 '(diff-hl-margin-insert ((t (:foreground "#54546D" :background "#252535"))))
 '(flycheck-posframe-background-face ((t (:background "#16161D"))))
 '(flycheck-posframe-face ((t (:inherit flycheck-posframe-background-face))))
 '(flycheck-posframe-info-face ((t (:foreground "#76946A" :background "#16161D"))))
 '(flycheck-posframe-warning-face ((t (:foreground "#7E9CD8" :background "#16161D"))))
 '(flycheck-posframe-error-face ((t (:foreground "#E82424" :background "#16161D"))))
 '(flycheck-fringe-warning ((t (:foreground "#7E9CD8"))))
 '(flycheck-fringe-error ((t (:foreground "#E82424"))))
 '(flycheck-fringe-info ((t (:foreground "#76946A"))))
 '(flycheck-error-list-warning ((t (:foreground "#FF9E3B" :weight bold))))
 '(flycheck-error-list-error ((t (:foreground "#E82424" :weight bold))))
 '(flycheck-error-list-info ((t (:foreground "#6A9589" :weight bold))))
 '(flycheck-inline-error ((t (:foreground "#E82424" :background "#43242B" :weight bold :height 138))))
 '(flycheck-inline-info ((t (:foreground "#7E9CD8" :background "#252535" :weight bold :height 138))))
 '(flycheck-inline-warning ((t (:foreground "#49443C" :background "#E6C384" :weight bold :height 138))))
 '(dashboard-heading ((t (:foreground "#9CABCA" :weight bold))))
 '(dashboard-banner-logo-title ((t (:weight bold :height 200))))
 '(dashboard-no-items-face ((t (:foreground "#2A2A37"))))
 '(popup-face ((t (:inherit tooltip))))
 '(popup-selection-face ((t (:inherit tooltip))))
 '(popup-tip-face ((t (:inherit tooltip))))
 '(orderless-match-face-0 ((t (:foreground "#76946A"))))
 '(orderless-match-face-1 ((t (:foreground "#957FB8"))))
 '(orderless-match-face-2 ((t (:foreground "#7E9CD8"))))
 '(orderless-match-face-3 ((t (:foreground "#6A9589"))))
 '(magit-blame-culprit ((t (:background "#2A2A37" :foreground "#C0A36E"))))
 '(magit-blame-date ((t (:background "#2A2A37" :foreground "#76946A"))))
 '(magit-blame-hash ((t (:background "#2A2A37" :foreground "#7E9CD8"))))
 '(magit-blame-header ((t (:background "#2A2A37" :foreground "#76946A"))))
 '(magit-blame-heading ((t (:background "#2A2A37" :foreground "#76946A"))))
 '(magit-blame-name ((t (:background "#2A2A37" :foreground "#C0A36E"))))
 '(magit-blame-sha1 ((t (:background "#2A2A37" :foreground "#7E9CD8"))))
 '(magit-blame-subject ((t (:background "#2A2A37" :foreground "#C0A36E"))))
 '(magit-blame-summary ((t (:background "#2A2A37" :foreground "#C0A36E" :extend t))))
 '(magit-blame-time ((t (:background "#2A2A37" :foreground "#76946A"))))
 '(magit-branch ((t (:foreground "#FFA066" :inherit bold))))
 '(magit-branch-current ((t (:background "#2A2A37" :foreground "#7E9CD8" :inherit bold :box t))))
 '(magit-branch-local ((t (:background "#2A2A37" :foreground "#7E9CD8" :inherit bold))))
 '(magit-branch-remote ((t (:background "#363646" :foreground "#7E9CD8" :inherit bold))))
 '(magit-diff-context-highlight ((t (:background "#1a1a22" :foreground "#DCD7BA" :extend t))))
 '(magit-diff-hunk-heading ((t (:background "#223249" :foreground "#DCD7BA" :extend t))))
 '(magit-diff-hunk-heading-highlight ((t (:background "#2D4F67" :foreground unspecified :extend t))))
 '(magit-hash ((t (:foreground nil))))
 '(magit-hunk-heading ((t (:background "#16161D" :extend t))))
 '(magit-hunk-heading-highlight ((t (:background "#363646" :extend t))))
 '(magit-item-highlight ((t (:background "#363646" :extend t))))
 '(magit-log-author ((t (:foreground "#7E9CD8"))))
 '(magit-log-head-label-head ((t (:background "#C0A36E" :foreground "#1F1F28" :inherit bold))))
 '(magit-log-head-label-local ((t (:background "#957FB8" :foreground "#1F1F28" :inherit bold))))
 '(magit-log-head-label-remote ((t (:background "#98BB6C" :foreground "#1F1F28" :inherit bold))))
 '(magit-log-head-label-tags ((t (:background "#957FB8" :foreground "#1F1F28" :inherit bold))))
 '(magit-log-head-label-wip ((t (:background "#6A9589" :foreground "#1F1F28" :inherit bold))))
 '(magit-log-sha1 ((t (:foreground "#98BB6C"))))
 '(magit-process-ng ((t (:foreground "#FF9E3B" :inherit bold))))
 '(magit-process-ok ((t (:foreground "#7E9CD8" :inherit bold))))
 '(magit-reflog-amend ((t (:foreground "#957FB8"))))
 '(magit-reflog-checkout ((t (:foreground "#7E9CD8"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#76946A"))))
 '(magit-reflog-commit ((t (:foreground "#76946A"))))
 '(magit-reflog-merge ((t (:foreground "#76946A"))))
 '(magit-reflog-other ((t (:foreground "#6A9589"))))
 '(magit-reflog-rebase ((t (:foreground "#957FB8"))))
 '(magit-reflog-remote ((t (:foreground "#6A9589"))))
 '(magit-reflog-reset ((t (:foreground "#C34043"))))
 '(magit-section-heading ((t (:foreground "#957FB8" :inherit bold :extend t))))
 '(magit-section-highlight ((t (:background "#181820" :extend t))))
 '(magit-section-title ((t (:background "#1F1F28" :foreground "#957FB8" :inherit bold))))
 '(dired-subtree-depth-1-face ((t (:background "#1F1F28"))))
 '(dired-subtree-depth-2-face ((t (:background "#1F1F28"))))
 '(dired-subtree-depth-3-face ((t (:background "#1F1F28"))))
 '(dired-subtree-depth-4-face ((t (:background "#1F1F28"))))
 '(dired-subtree-depth-5-face ((t (:background "#1F1F28"))))
 '(dired-subtree-depth-6-face ((t (:background "#1F1F28"))))
 '(corfu-default ((t (:background "#1a1a22"))))
 '(corfu-current ((t (:background "#363646" :foreground nil))))
 '(corfu-deprecated ((t (:inherit nil))))
 '(corfu-bar ((t (:background nil :inherit tooltip))))
 '(corfu-border ((t (:background "#1F1F28"))))
 '(wgrep-face ((t (:foreground "#76946A"))))
 '(wgrep-delete-face ((t (:foreground "#C34043"))))
 '(wgrep-reject-face ((t (:foreground "#C34043"))))
 '(wgrep-file-face ((t (:foreground "#76946A"))))
 '(wgrep-done-face ((t (:foreground "#7E9CD8"))))
 '(diredfl-autofile-name ((t (:foreground "#2D4F67"))))
 '(diredfl-compressed-file-name ((t (:foreground "#49443C"))))
 '(diredfl-compressed-file-suffix ((t (:foreground "#DCA561"))))
 '(diredfl-date-time ((t (:foreground "#957FB8"))))
 '(diredfl-deletion ((t (:background "#FF9E3B" :foreground "#E82424"))))
 '(diredfl-deletion-file-name ((t (:foreground "#E82424"))))
 '(diredfl-dir-heading ((t (:foreground "#7FB4CA"))))
 '(diredfl-dir-name ((t (:foreground "#957FB8"))))
 '(diredfl-dir-priv ((t (:foreground "#957FB8"))))
 '(diredfl-exec-priv ((t (:foreground "#7E9CD8"))))
 '(diredfl-executable-tag ((t (:foreground "#C34043"))))
 '(diredfl-file-name ((t (:foreground "#DCD7BA"))))
 '(diredfl-file-suffix ((t (:foreground "#957FB8"))))
 '(diredfl-flag-mark ((t (:foreground "#C0A36E"))))
 '(diredfl-flag-mark-line ((t (:foreground "#7FB4CA"))))
 '(diredfl-ignored-file-name ((t (:foreground "#6A9589"))))
 '(diredfl-link-priv ((t (:foreground "#FFA066"))))
 '(diredfl-no-priv ((t (:foreground "#DCD7BA"))))
 '(diredfl-number ((t (:foreground "#FFA066"))))
 '(diredfl-other-priv ((t (:foreground "#E6C384"))))
 '(diredfl-rare-priv ((t (:foreground "#957FB8"))))
 '(diredfl-read-priv ((t (:foreground "#6A9589"))))
 '(diredfl-symlink ((t (:foreground "#7FB4CA"))))
 '(diredfl-tagged-autofile-name ((t (:foreground "#98BB6C"))))
 '(diredfl-write-priv ((t (:foreground "#DCD7BA"))))
 '(markdown-header-delimiter-face ((t (:foreground "#54546D" :background "#1F1F28"))))
 '(markdown-markup-face ((t (:foreground "#54546D" :background "#1F1F28"))))
 '(default ((t (:foreground "#DCD7BA" :background "#1F1F28")))))

(provide-theme 'kanagawa-wave)
