;;; package -- Summary
;;; Code:
;;; Commentary:
;;; This part is autogenerated
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(python-black js2-mode prettier-js lsp-pyright python-mode typescript-mode evil cmake-mode)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;; MAIN CONFIG
;; ========================================

(load-file "~/.config/emacs/packages.el")

;; Disable menus
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
;; Disable startup screen
(setq inhibit-startup-screen t)
;; Convert tabs to spaces
(setq-default indent-tabs-mode nil)
;; Font
(set-face-attribute 'default nil :font "FiraMono Nerd Font" :height 140)
(when (member "Noto Color Emoji" (font-family-list))
  (set-fontset-font
    t 'symbol (font-spec :family "Noto Color Emoji") nil 'prepend))
;; Enable line numbers globally
(global-display-line-numbers-mode)
;; Disable backup file
(setq make-backup-files nil)
;; Set theme
(unless (package-installed-p 'autothemer)
  (package-install 'autothemer))
(load-file "~/.config/emacs/kanagawa-theme.el")
(load-theme 'kanagawa t)
;; (load-theme 'wombat t)
;; Go 20 lines down
(global-set-key (kbd "C-S-n") (lambda () (interactive) (forward-line 20)))
(global-set-key (kbd "C-S-p") (lambda () (interactive) (forward-line -20)))

;; Enable emojify
(require 'emojify)
(add-hook 'after-init-hook #'global-emojify-mode)
;; Enable projectile
(require 'projectile)
(projectile-mode 1)
;; Enable recentf
(require 'recentf)
(recentf-mode 1)
;; Enable company
(require 'company)
(global-company-mode 1)
;; Enable ivy for autocomplete
(require 'ivy)
(ivy-mode 1)
;; Enable flycheck
(require 'flycheck)
(global-flycheck-mode 1)

(define-prefix-command 'c-l)
(global-set-key (kbd "C-l") nil)
(global-set-key (kbd "C-l") 'c-l)
;; (global-set-key (kbd "C-x f") nil)
(load-file "~/.config/emacs/grep-project.el")

;; Projectile keybinds
(define-key 'c-l (kbd "p p") 'projectile-switch-project)
(define-key 'c-l (kbd "f f") 'projectile-switch-project)

;; Open terminal in current project
(defun my-open-terminal()
  "Opens terminal at the current project root."
  (interactive)
  (let ((project-root (projectile-project-root)))
    (if project-root
        (let ((default-directory project-root))
          (ansi-term (getenv "SHELL"))))))
(define-key 'c-l (kbd "M-t") 'my-open-terminal)

;; Recentf keybinds
(define-key 'c-l (kbd "f r") 'recentf)

(load-file "~/.config/emacs/lsp-setup.el")

;; Set the path to the Node.js binary
(let ((node-path "/home/shuvo/.nvm/versions/node/v20.11.1/bin"))
  (setq exec-path (append exec-path (list node-path)))
  (setenv "PATH" (concat node-path ":" (getenv "PATH"))))

(load-file "~/.config/emacs/typescript-setup.el")

(load-file "~/.config/emacs/javascript-setup.el")

(load-file "~/.config/emacs/python-setup.el")

;;; init.el ends here

