#!/usr/bin/env bash

BLUE=$'\e[38;5;4m'
GREEN=$'\e[38;5;2m'
YELLOW=$'\e[38;5;3m'
CYAN=$'\e[38;5;6m'
RESET=$'\e[0m'

FILENAME=$1
shift

git blame --date=short --minimal "$@" "$FILENAME" | sed -E "s/^(\^?\w+) (.+)\s+([0-9]{4}-[0-9]{2}-[0-9]{2})\s+([0-9]+)\)/${CYAN}\1${RESET} ${YELLOW}\2${RESET} ${GREEN}\3${RESET} ${BLUE}\4)${RESET}/"
