#!/usr/bin/env bash

BLUE="\x1b[1;34m"
GREEN="\x1b[1;32m"
YELLOW="\x1b[1;33m"
CYAN="\x1b[1;36m"
RESET="\x1b[0m"

FILENAME=$1
shift

git blame --date=short --minimal "$@" "$FILENAME" | sed -E "s/^(\w+) (.+)\s+([0-9]{4}-[0-9]{2}-[0-9]{2})\s+([0-9]+)\)/${CYAN}\1${RESET} ${YELLOW}\2${RESET} ${GREEN}\3${RESET} ${BLUE}\4)${RESET}/"
