#!/usr/bin/env bash

# kitty_command=~/.local/kitty.app/bin/kitten
kitty_command=kitten
window_name="$1"

sockets=$(ls -1tr /tmp/kitty-$(whoami)-*)

for socket in $sockets; do
    window_id=$($kitty_command @ --to unix:"$socket" ls | jq -r --arg window_name "$window_name" '.[].tabs[].windows[] | select(.title == $window_name).id')

    if [[ -n "$window_id" ]]; then
        unix_socket="$socket"

        $kitty_command @ --to unix:"$unix_socket" focus-window --match id:"$window_id"

        sleep 0.1

        hyprctl dispatch focuswindow title:^"$window_name"$
        break
    fi
done
