#!/usr/bin/env bash

window_name="$1"

unix_socket=$(ls -1tr /tmp/kitty-$(whoami)-* | sort -k 2 | head -n 1)

if [[ -z "$unix_socket" ]]; then
    notify-send "Error: No kitty socket found"
    exit 1
fi

window_id=$(~/.local/kitty.app/bin/kitten @ --to unix:"$unix_socket" ls | jq -r --arg window_name "$window_name" '.[].tabs[] | select(.title == $window_name).windows[] | select(.title == $window_name).id')

if [[ -z "$window_id" ]]; then
    notify-send "Error: Window '$window_name' not found"
    exit 1
fi

~/.local/kitty.app/bin/kitten @ --to unix:"$unix_socket" focus-window --match id:"$window_id"

sleep 0.1

hyprctl dispatch focuswindow title:"$window_name"
