#!/usr/bin/env bash

# kitty_command=~/.local/kitty.app/bin/kitten
kitty_command=kitten
sockets=$(ls -1tr /tmp/kitty-$(whoami)-*)

windows=()
for socket in $sockets; do
    window_name=$($kitty_command @ --to unix:"$socket" ls | jq -r --arg window_name "$window_name" '.[].tabs[].windows[].title')

    windows+=("$window_name")
done

window_name=$(printf "%s\n" "${windows[@]}" | fzf)

hyprkittyswitcher "$window_name"
