#!/usr/bin/env bash

dconf load /org/gnome/desktop/wm/ < wm-keybindings.conf
dconf load /org/gnome/shell/keybindings/ < shell-keybindings.conf
dconf load /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/ < custom-keybindings.conf
