#!/usr/bin/env bash

version="29.4"

cd $HOME/make-builds/

if [[ ! -e $HOME/make-builds/emacs-emacs-$version ]]; then
    echo "Downloading emacs..."
    curl -o emacs-$version.tar.gz https://codeload.github.com/emacs-mirror/emacs/tar.gz/refs/tags/emacs-$version

    echo "Unpacking emacs-$version"
    tar xvf emacs-$version.tar.gz

    echo "Removing tarball"
    rm emacs-$version.tar.gz
fi

cd emacs-emacs-$version

gcc_version=$(gcc --version | head -n 1 | awk '{print $4}' | sed 's/^\([0-9]*\)\..*/\1/')

echo "Installing dependencies..."
sudo apt install libgccjit-$gcc_version-dev libtree-sitter-dev libjansson-dev imagemagick autoconf texinfo libmagickwand-dev libxpm-dev libgif-dev libgnutls28-dev

if [[ ! -e $HOME/make-builds/emacs/configure ]]; then
    ./autogen.sh
fi

echo "Configuring..."
./configure --with-native-compilation --with-tree-sitter --with-json --with-imagemagick --without-pop --with-x-toolkit=no

echo "Installing..."
make -j$(nproc)

sudo make install

echo "Cleaning up..."

make clean
make distclean

echo "Emacs $version installed"
