#!/usr/bin/env bash

title='platform'
fe_path='~/src/ManzilApp/platform-fe'
be_path='~/src/ManzilApp/platform-be'

kitten @ launch --cwd $be_path --type os-window --env ${title}_TAB=be --title ${title}-be
kitten @ launch --cwd $fe_path --type tab --env ${title}_TAB=fe --title ${title}-fe
kitten @ launch --cwd $be_path --type tab --env ${title}_TAB=be-server --title "be-server"
kitten @ launch --cwd $fe_path --type tab --env ${title}_TAB=fe-server --title "fe-server"

kitten @ send-text --match "env:${title}_TAB=be" "pyenv activate platform-be\nclear\n"
kitten @ send-text --match "env:${title}_TAB=be-server" "pyenv activate platform-be\nclear\n"

kitten @ action goto_tab 1
