#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Name to change was not provided"
    exit 1
fi

if [ -z "$2" ]; then
    echo "New name was not provided"
    exit 1
fi

for f in $(ls | grep $1); do
    echo "Renaming $f to $(echo $f | sed "s/$1/$2/")"
    mv $f $(echo $f | sed "s/$1/$2/")
done

echo "Renaming done..."
