#!/usr/bin/env bash

function create_session_and_window() {
    tmux new -ds platform -c $HOME/src/ManzilApp/platform-$1
    tmux rename-window -t platform:1 $1
}

function create_new_window() {
    tmux new-window -t platform -n $2 -c $HOME/src/ManzilApp/platform-$1
}

function activate_virtualenv() {
    tmux send-keys -t platform:$1 "source .venv/bin/activate" C-m
    tmux send-keys -t platform:$1 "clear" C-m
}

function switch_to_window() {
    if [[ -z $TMUX ]]; then
        tmux a -t platform:$1
    else
        tmux switch-client -t platform:$1
    fi
}

if [[ -z $1 ]]; then
    tmux has-session -t platform 2>/dev/null
    if [[ $? == 1 ]]; then
        create_session_and_window be
        activate_virtualenv be
        create_new_window fe fe
        create_new_window be be-server
        activate_virtualenv be-server
        create_new_window fe fe-server
    fi
    switch_to_window be
elif [[ $1 == "be" ]]; then
    tmux has-session -t platform 2>/dev/null
    if [[ $? == 1 ]]; then
        create_session_and_window be
        activate_virtualenv be
        create_new_window be be-server
        activate_virtualenv be-server
    fi
    switch_to_window be 2>/dev/null
    if [[ $? == 1 ]]; then
        create_new_window be be
        activate_virtualenv be
        create_new_window be be-server
        activate_virtualenv be-server
        switch_to_window be
    fi
elif [[ $1 == "fe" ]]; then
    tmux has-session -t platform 2>/dev/null
    if [[ $? == 1 ]]; then
        create_session_and_window fe
    fi
    switch_to_window fe 2/dev/null
    if [[ $? == 1 ]]; then
        create_new_window fe fe
        switch_to_window fe
    fi
else
    echo "ERROR: Wrong parameter"
    exit 1
fi
