#!/usr/bin/env bash

function find_relevant_directories() {
    directories=$(find ~/src ~/Documents ~/projscripts ~/postgresql ~/dotfiles -type d \( -name node_modules -o -name .git -o -name __pycache__ \) -prune -o -type d -print | fzf)
    echo $directories
}
